### ISSUE TITLE
Error build

### ISSUE THREAD

**Issue by CargoBlitzUser** [Ncleardev/NclearOS#1]
1>------ Build started: Project: NclearOS, Configuration: Debug|AnyCPU ------
1>C:\Program Files\dotnet\sdk\7.0.201\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'net5.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.
1>C:\Program Files\dotnet\sdk\7.0.201\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error NETSDK1004: Assets file 'C:\Users\Admin\Downloads\CO---OS DEV\NclearOS\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
Build failed.
help please

**Comment by Ncleardev** [comment]
Make sure VS 2022 and Cosmos [User Kit 20221121](https://github.com/CosmosOS/Cosmos/releases/tag/UserKit_20221121) are installed. Open VS 2022 and create new Cosmos project. Then download this [zip file](https://github.com/Ncleardev/NclearOS/archive/refs/heads/main.zip) and move contents of "NclearOS" folder to recently created project.
![final result](https://user-images.githubusercontent.com/99822900/222854657-9348df9c-8dce-4157-982c-cf74118477c1.png)
**Also remove the original Kernel.cs**

More information: https://ncleardev.github.io/nclearos-faq

**Comment by CargoBlitzUser** [comment]
Thanks for your help
