### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by CargoBlitzUser** [Ncleardev/NclearOS#2]
MSB6006 "yasm.exe" exited with code - 1073741515

**Comment by Ncleardev** [comment]
This error is a result of missing .dll files

https://github.com/CosmosOS/Cosmos/issues/2102#issuecomment-1033642179
> Ok everyone see these issues now I can fix them. these issues happen to be like yasm.exe cannot find a Microsoft Visual C++ 2010 Service Pack after I install Microsoft Visual C++ 2010 Service Pack I can build and everything is good. Link: https://www.microsoft.com/en-us/download/details.aspx?id=26999 This can be fixed with the last devkit on now.

If the problem still persists, reinstall Cosmos [(newest Installation guide)](https://cosmosos.github.io/install.html)

**Comment by CargoBlitzUser** [comment]
Thanks again!
